spring:
  datasource:
    url: "jdbc:h2:mem:mydb"
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: create
